description: 'description'
current_fate_points: 'current_fate_points'
name: 'name'
trouble: 'trouble'
high_concept: 'high_concept'
aspect3: 'aspect3'
aspect4: 'aspect4'
aspect5: 'aspect5'
refresh: 'refresh'
careful: 'careful'
clever: 'clever'
flashy: 'flashy'
quick: 'quick'
forceful: 'forceful'
sneaky: 'sneaky'
stunts: 'stunts'
moderate: 'moderate'
mild: 'mild'
severe: 'severe'
