player: "Player"
height: "Height"
weight: "Weight"
size_modifier: "Size Modifiear"
age: "Age"
st: "ST"
stcost: "STcost"
dx: "DX"
dxcost: "DXcost"
iq: "IQ"
iqcost: "IQcost"
ht: "HT"
hp: "HP"
will: "Will"
fp: "FP"
hpcurrent: "HPcurrent"
fpcurrent: "FPcurrent"
hpcost: "HPcost"
willcost: "Willcost"
percost: "Percost"
fpcost: "FPcost"
thrust: "Thrust"
swing: "Swing"
htcost: "HTcost"
bscost: "BScost"
bmcost: "BMcost"
basic_lift: "BasicLift"
basic_speed: "BasicSpeed"
point_total: "PointTotal"
unspent_points: "UnspentPoints"
basic_move: "BasicMove"
enc_none: "EncNone"
enc_light: "EncLight"
enc_medium: "EncMedium"
enc_heavy: "EncHeavy"
enc_xheavy: "EncXHeavy"
bmlight: "BMLight"
bmmedium: "BMMedium"
bmheavy: "BMHeavy"
bmxheavy: "BMXHeavy"
bmnone: "BMNone"
dodgenone: "DodgeNone"
dodgelight: "DodgeLight"
dodgemedium: "DodgeMedium"
dodgeheavy: "DodgeHeavy"
dodgexheavy: "DodgeXHeavy"
advantages_0: "Advantages.0"
advantages_1: "Advantages.1"
advantages_2: "Advantages.2"
advantages_3: "Advantages.3"
advantages_4: "Advantages.4"
advantages_5: "Advantages.5"
advantages_6: "Advantages.6"
advantages_7: "Advantages.7"
advantages_8: "Advantages.8"
advantages_9: "Advantages.9"
advantages_10: "Advantages.10"
advantages_11: "Advantages.11"
advcost_1: "AdvCost.1"
advcost_2: "AdvCost.2"
advcost_3: "AdvCost.3"
advcost_4: "AdvCost.4"
advcost_5: "AdvCost.5"
advcost_6: "AdvCost.6"
advcost_7: "AdvCost.7"
advcost_8: "AdvCost.8"
advcost_9: "AdvCost.9"
advcost_10: "AdvCost.10"
advcost_11: "AdvCost.11"
advcost_0: "AdvCost.0"
sumatts: "SumAtts"
disadvantages_2: "Disadvantages.2"
disadvantages_1: "Disadvantages.1"
disadvantages_0: "Disadvantages.0"
disadvantages_3: "Disadvantages.3"
disadvantages_4: "Disadvantages.4"
disadvantages_5: "Disadvantages.5"
disadvantages_6: "Disadvantages.6"
disadvantages_7: "Disadvantages.7"
disadvantages_8: "Disadvantages.8"
disadvantages_9: "Disadvantages.9"
disadvantages_10: "Disadvantages.10"
disadvantages_11: "Disadvantages.11"
disadvantages_12: "Disadvantages.12"
disadcost_12: "DisadCost.12"
disadcost_11: "DisadCost.11"
disadcost_10: "DisadCost.10"
disadcost_9: "DisadCost.9"
disadcost_8: "DisadCost.8"
disadcost_7: "DisadCost.7"
disadcost_6: "DisadCost.6"
disadcost_5: "DisadCost.5"
disadcost_4: "DisadCost.4"
disadcost_3: "DisadCost.3"
disadcost_2: "DisadCost.2"
disadcost_1: "DisadCost.1"
disadcost_0: "DisadCost.0"
sumads: "SumAds"
skill_1: "Skill.1"
skill_3: "Skill.3"
skill_4: "Skill.4"
skill_5: "Skill.5"
skill_6: "Skill.6"
skill_7: "Skill.7"
skill_8: "Skill.8"
skill_9: "Skill.9"
skill_10: "Skill.10"
skill_11: "Skill.11"
skill_12: "Skill.12"
skill_13: "Skill.13"
skill_14: "Skill.14"
skill_15: "Skill.15"
skill_16: "Skill.16"
skill_17: "Skill.17"
skill_18: "Skill.18"
skill_19: "Skill.19"
skill_20: "Skill.20"
skill_21: "Skill.21"
skill_22: "Skill.22"
skill_2: "Skill.2"
skill_23: "Skill.23"
skill_24: "Skill.24"
skill_0: "Skill.0"
level_0: "Level.0"
level_1: "Level.1"
level_3: "Level.3"
level_4: "Level.4"
level_5: "Level.5"
level_6: "Level.6"
level_7: "Level.7"
level_8: "Level.8"
level_9: "Level.9"
level_10: "Level.10"
level_11: "Level.11"
level_12: "Level.12"
level_13: "Level.13"
level_14: "Level.14"
level_15: "Level.15"
level_16: "Level.16"
level_17: "Level.17"
level_18: "Level.18"
level_19: "Level.19"
level_20: "Level.20"
level_21: "Level.21"
level_22: "Level.22"
level_2: "Level.2"
level_23: "Level.23"
level_24: "Level.24"
rellevel_0: "RelLevel.0"
rellevel_1: "RelLevel.1"
rellevel_3: "RelLevel.3"
rellevel_4: "RelLevel.4"
rellevel_5: "RelLevel.5"
rellevel_6: "RelLevel.6"
rellevel_7: "RelLevel.7"
rellevel_8: "RelLevel.8"
rellevel_9: "RelLevel.9"
rellevel_10: "RelLevel.10"
rellevel_11: "RelLevel.11"
rellevel_12: "RelLevel.12"
rellevel_13: "RelLevel.13"
rellevel_14: "RelLevel.14"
rellevel_15: "RelLevel.15"
rellevel_16: "RelLevel.16"
rellevel_17: "RelLevel.17"
rellevel_18: "RelLevel.18"
rellevel_19: "RelLevel.19"
rellevel_20: "RelLevel.20"
rellevel_21: "RelLevel.21"
rellevel_22: "RelLevel.22"
rellevel_2: "RelLevel.2"
rellevel_23: "RelLevel.23"
rellevel_24: "RelLevel.24"
skcost_1: "SKcost.1"
skcost_3: "SKcost.3"
skcost_4: "SKcost.4"
skcost_5: "SKcost.5"
skcost_6: "SKcost.6"
skcost_7: "SKcost.7"
skcost_8: "SKcost.8"
skcost_9: "SKcost.9"
skcost_10: "SKcost.10"
skcost_11: "SKcost.11"
skcost_12: "SKcost.12"
skcost_13: "SKcost.13"
skcost_14: "SKcost.14"
skcost_15: "SKcost.15"
skcost_16: "SKcost.16"
skcost_17: "SKcost.17"
skcost_18: "SKcost.18"
skcost_19: "SKcost.19"
skcost_20: "SKcost.20"
skcost_21: "SKcost.21"
skcost_22: "SKcost.22"
skcost_2: "SKcost.2"
skcost_23: "SKcost.23"
skcost_24: "SKcost.24"
skcost_0: "SKcost.0"
sumdisads: "SumDisads"
language_1: "Language.1"
language_2: "Language.2"
language_3: "Language.3"
language_4: "Language.4"
language_0: "Language.0"
spoken_0: "Spoken.0"
spoken_1: "Spoken.1"
spoken_2: "Spoken.2"
spoken_3: "Spoken.3"
spoken_4: "Spoken.4"
written_0: "Written.0"
written_1: "Written.1"
written_2: "Written.2"
written_3: "Written.3"
written_4: "Written.4"
langcost_1: "Langcost.1"
langcost_2: "Langcost.2"
langcost_3: "Langcost.3"
langcost_4: "Langcost.4"
langcost_0: "Langcost.0"
perception: "Perception"
parry: "Parry"
block: "Block"
techlevel: "TechLevel"
tlcost: "TLcost"
cultfam_0: "CultFam.0"
cultfam_1: "CultFam.1"
cultfam_2: "CultFam.2"
cfcost_0: "CFcost.0"
cfcost_1: "CFcost.1"
cfcost_2: "CFcost.2"
appearance: "Appearance"
status: "Status"
reputation_0: "Reputation.0"
reputation_1: "Reputation.1"
reputation_2: "Reputation.2"
reputation_3: "Reputation.3"
reputation_4: "Reputation.4"
sumskills: "SumSkills"
sumother: "SumOther"
name: "Name"
hwname_1: "HWName.1"
hwname_2: "HWName.2"
hwname_3: "HWName.3"
hwname_4: "HWName.4"
hwname_0: "HWName.0"
hwdamage_1: "HWDamage.1"
hwdamage_2: "HWDamage.2"
hwdamage_3: "HWDamage.3"
hwdamage_4: "HWDamage.4"
hwdamage_0: "HWDamage.0"
hwreach_1: "HWReach.1"
hwreach_2: "HWReach.2"
hwreach_3: "HWReach.3"
hwreach_4: "HWReach.4"
hwreach_0: "HWReach.0"
hwparry_1: "HWParry.1"
hwparry_2: "HWParry.2"
hwparry_3: "HWParry.3"
hwparry_4: "HWParry.4"
hwparry_0: "HWParry.0"
hwnotes_1: "HWNotes.1"
hwnotes_2: "HWNotes.2"
hwnotes_3: "HWNotes.3"
hwnotes_4: "HWNotes.4"
hwnotes_0: "HWNotes.0"
hwcost_1: "HWCost.1"
hwcost_2: "HWCost.2"
hwcost_3: "HWCost.3"
hwcost_4: "HWCost.4"
hwcost_0: "HWCost.0"
hwweight_1: "HWWeight.1"
hwweight_2: "HWWeight.2"
hwweight_3: "HWWeight.3"
hwweight_4: "HWWeight.4"
hwweight_0: "HWWeight.0"
rwname_0: "RWName.0"
rwname_1: "RWName.1"
rwname_2: "RWName.2"
rwname_3: "RWName.3"
rwname_4: "RWName.4"
rwname_5: "RWName.5"
rwname_6: "RWName.6"
rwname_7: "RWName.7"
rwname_8: "RWName.8"
rwname_9: "RWName.9"
rwdamage_0: "RWDamage.0"
rwdamage_1: "RWDamage.1"
rwdamage_2: "RWDamage.2"
rwdamage_3: "RWDamage.3"
rwdamage_4: "RWDamage.4"
rwdamage_5: "RWDamage.5"
rwdamage_6: "RWDamage.6"
rwdamage_7: "RWDamage.7"
rwdamage_8: "RWDamage.8"
rwdamage_9: "RWDamage.9"
rwacc_0: "RWAcc.0"
rwacc_1: "RWAcc.1"
rwacc_2: "RWAcc.2"
rwacc_3: "RWAcc.3"
rwacc_4: "RWAcc.4"
rwacc_5: "RWAcc.5"
rwacc_6: "RWAcc.6"
rwacc_7: "RWAcc.7"
rwacc_8: "RWAcc.8"
rwacc_9: "RWAcc.9"
rwrange_0: "RWRange.0"
rwrange_1: "RWRange.1"
rwrange_2: "RWRange.2"
rwrange_3: "RWRange.3"
rwrange_4: "RWRange.4"
rwrange_5: "RWRange.5"
rwrange_6: "RWRange.6"
rwrange_7: "RWRange.7"
rwrange_8: "RWRange.8"
rwrange_9: "RWRange.9"
rwrof_0: "RWRof.0"
rwrof_1: "RWRof.1"
rwrof_2: "RWRof.2"
rwrof_3: "RWRof.3"
rwrof_4: "RWRof.4"
rwrof_5: "RWRof.5"
rwrof_6: "RWRof.6"
rwrof_7: "RWRof.7"
rwrof_8: "RWRof.8"
rwrof_9: "RWRof.9"
rwshots_0: "RWShots.0"
rwshots_1: "RWShots.1"
rwshots_2: "RWShots.2"
rwshots_3: "RWShots.3"
rwshots_4: "RWShots.4"
rwshots_5: "RWShots.5"
rwshots_6: "RWShots.6"
rwshots_7: "RWShots.7"
rwshots_8: "RWShots.8"
rwshots_9: "RWShots.9"
rwst_0: "RWST.0"
rwst_1: "RWST.1"
rwst_2: "RWST.2"
rwst_3: "RWST.3"
rwst_4: "RWST.4"
rwst_5: "RWST.5"
rwst_6: "RWST.6"
rwst_7: "RWST.7"
rwst_8: "RWST.8"
rwst_9: "RWST.9"
rwbulk_0: "RWBulk.0"
rwbulk_1: "RWBulk.1"
rwbulk_2: "RWBulk.2"
rwbulk_3: "RWBulk.3"
rwbulk_4: "RWBulk.4"
rwbulk_5: "RWBulk.5"
rwbulk_6: "RWBulk.6"
rwbulk_7: "RWBulk.7"
rwbulk_8: "RWBulk.8"
rwbulk_9: "RWBulk.9"
rwrcl_0: "RWRcl.0"
rwrcl_1: "RWRcl.1"
rwrcl_2: "RWRcl.2"
rwrcl_3: "RWRcl.3"
rwrcl_4: "RWRcl.4"
rwrcl_5: "RWRcl.5"
rwrcl_6: "RWRcl.6"
rwrcl_7: "RWRcl.7"
rwrcl_8: "RWRcl.8"
rwrcl_9: "RWRcl.9"
rwlc_0: "RWLC.0"
rwlc_1: "RWLC.1"
rwlc_2: "RWLC.2"
rwlc_3: "RWLC.3"
rwlc_4: "RWLC.4"
rwlc_5: "RWLC.5"
rwlc_6: "RWLC.6"
rwlc_7: "RWLC.7"
rwlc_8: "RWLC.8"
rwlc_9: "RWLC.9"
rwnotes_0: "RWNotes.0"
rwnotes_1: "RWNotes.1"
rwnotes_2: "RWNotes.2"
rwnotes_3: "RWNotes.3"
rwnotes_4: "RWNotes.4"
rwnotes_5: "RWNotes.5"
rwnotes_6: "RWNotes.6"
rwnotes_7: "RWNotes.7"
rwnotes_8: "RWNotes.8"
rwnotes_9: "RWNotes.9"
rwcost_0: "RWCost.0"
rwcost_1: "RWCost.1"
rwcost_2: "RWCost.2"
rwcost_3: "RWCost.3"
rwcost_4: "RWCost.4"
rwcost_5: "RWCost.5"
rwcost_6: "RWCost.6"
rwcost_7: "RWCost.7"
rwcost_8: "RWCost.8"
rwcost_9: "RWCost.9"
rwweight_0: "RWWeight.0"
rwweight_1: "RWWeight.1"
rwweight_2: "RWWeight.2"
rwweight_3: "RWWeight.3"
rwweight_4: "RWWeight.4"
rwweight_5: "RWWeight.5"
rwweight_6: "RWWeight.6"
rwweight_7: "RWWeight.7"
rwweight_8: "RWWeight.8"
rwweight_9: "RWWeight.9"
item_0: "Item.0"
item_1: "Item.1"
item_2: "Item.2"
item_3: "Item.3"
item_4: "Item.4"
item_5: "Item.5"
item_6: "Item.6"
item_7: "Item.7"
item_8: "Item.8"
item_9: "Item.9"
item_10: "Item.10"
item_11: "Item.11"
item_12: "Item.12"
item_13: "Item.13"
item_14: "Item.14"
item_15: "Item.15"
item_16: "Item.16"
item_17: "Item.17"
item_18: "Item.18"
item_19: "Item.19"
item_20: "Item.20"
item_21: "Item.21"
item_22: "Item.22"
item_23: "Item.23"
item_24: "Item.24"
item_25: "Item.25"
item_26: "Item.26"
item_27: "Item.27"
item_28: "Item.28"
item_29: "Item.29"
item_30: "Item.30"
item_31: "Item.31"
item_32: "Item.32"
item_33: "Item.33"
itemloc_0: "ItemLoc.0"
itemloc_1: "ItemLoc.1"
itemloc_2: "ItemLoc.2"
itemloc_3: "ItemLoc.3"
itemloc_4: "ItemLoc.4"
itemloc_5: "ItemLoc.5"
itemloc_6: "ItemLoc.6"
itemloc_7: "ItemLoc.7"
itemloc_8: "ItemLoc.8"
itemloc_9: "ItemLoc.9"
itemloc_10: "ItemLoc.10"
itemloc_11: "ItemLoc.11"
itemloc_12: "ItemLoc.12"
itemloc_13: "ItemLoc.13"
itemloc_14: "ItemLoc.14"
itemloc_15: "ItemLoc.15"
itemloc_16: "ItemLoc.16"
itemloc_17: "ItemLoc.17"
itemloc_18: "ItemLoc.18"
itemloc_19: "ItemLoc.19"
itemloc_20: "ItemLoc.20"
itemloc_21: "ItemLoc.21"
itemloc_22: "ItemLoc.22"
itemloc_23: "ItemLoc.23"
itemloc_24: "ItemLoc.24"
itemloc_25: "ItemLoc.25"
itemloc_26: "ItemLoc.26"
itemloc_27: "ItemLoc.27"
itemloc_28: "ItemLoc.28"
itemloc_29: "ItemLoc.29"
itemloc_30: "ItemLoc.30"
itemloc_31: "ItemLoc.31"
itemloc_32: "ItemLoc.32"
itemloc_33: "ItemLoc.33"
itemcost_0: "ItemCost.0"
itemcost_1: "ItemCost.1"
itemcost_2: "ItemCost.2"
itemcost_3: "ItemCost.3"
itemcost_4: "ItemCost.4"
itemcost_5: "ItemCost.5"
itemcost_6: "ItemCost.6"
itemcost_7: "ItemCost.7"
itemcost_8: "ItemCost.8"
itemcost_9: "ItemCost.9"
itemcost_10: "ItemCost.10"
itemcost_11: "ItemCost.11"
itemcost_12: "ItemCost.12"
itemcost_13: "ItemCost.13"
itemcost_14: "ItemCost.14"
itemcost_15: "ItemCost.15"
itemcost_16: "ItemCost.16"
itemcost_17: "ItemCost.17"
itemcost_18: "ItemCost.18"
itemcost_19: "ItemCost.19"
itemcost_20: "ItemCost.20"
itemcost_21: "ItemCost.21"
itemcost_22: "ItemCost.22"
itemcost_23: "ItemCost.23"
itemcost_24: "ItemCost.24"
itemcost_25: "ItemCost.25"
itemcost_26: "ItemCost.26"
itemcost_27: "ItemCost.27"
itemcost_28: "ItemCost.28"
itemcost_29: "ItemCost.29"
itemcost_30: "ItemCost.30"
itemcost_31: "ItemCost.31"
itemcost_32: "ItemCost.32"
itemcost_33: "ItemCost.33"
itemweight_0: "ItemWeight.0"
itemweight_1: "ItemWeight.1"
itemweight_2: "ItemWeight.2"
itemweight_3: "ItemWeight.3"
itemweight_4: "ItemWeight.4"
itemweight_5: "ItemWeight.5"
itemweight_6: "ItemWeight.6"
itemweight_7: "ItemWeight.7"
itemweight_8: "ItemWeight.8"
itemweight_9: "ItemWeight.9"
itemweight_10: "ItemWeight.10"
itemweight_11: "ItemWeight.11"
itemweight_12: "ItemWeight.12"
itemweight_13: "ItemWeight.13"
itemweight_14: "ItemWeight.14"
itemweight_15: "ItemWeight.15"
itemweight_16: "ItemWeight.16"
itemweight_17: "ItemWeight.17"
itemweight_18: "ItemWeight.18"
itemweight_19: "ItemWeight.19"
itemweight_20: "ItemWeight.20"
itemweight_21: "ItemWeight.21"
itemweight_22: "ItemWeight.22"
itemweight_23: "ItemWeight.23"
itemweight_24: "ItemWeight.24"
itemweight_25: "ItemWeight.25"
itemweight_26: "ItemWeight.26"
itemweight_27: "ItemWeight.27"
itemweight_28: "ItemWeight.28"
itemweight_29: "ItemWeight.29"
itemweight_30: "ItemWeight.30"
itemweight_31: "ItemWeight.31"
itemweight_32: "ItemWeight.32"
itemweight_33: "ItemWeight.33"
totalweight: "TotalWeight"
totalcost: "TotalCost"
characternotes_0: "CharacterNotes.0"
characternotes_1: "CharacterNotes.1"
characternotes_2: "CharacterNotes.2"
characternotes_3: "CharacterNotes.3"
characternotes_6: "CharacterNotes.6"
characternotes_7: "CharacterNotes.7"
characternotes_8: "CharacterNotes.8"
characternotes_5: "CharacterNotes.5"
characternotes_4: "CharacterNotes.4"
appearancereaction: "AppearanceReaction"
dr: "DR"
drleg: "DRLeg"
drhand: "DRHand"
drtorso: "DRTorso"
drhead: "DRHead"
drarm: "DRArm"
drfoot: "DRFoot"
parrynote: "ParryNote"
