# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33e6f08696d40348393b2240e60b50cc4aacd853f050d9f8746586a41377179582c1f80c58ff7e38be9914a8b0e605d04c689d44cf3e5586a99379fcfd78aea7

test:
  secret_key_base: be6686e166d81292154ff43db322fad2490facefd5cd79a72f750713d98574da4723ae2f218c5c5455b334362ce1878c8a6409c96c62acf3261606a50b524987

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
